### PR TITLE
Adjust "before prepare" hook

### PR DESCRIPTION
**Pull request by pat-s**
Since the underlying image is now using debian instead of alpine.

### CODE REVIEW

**Comment by pat-s** [comment]
ping @anbraten @xoxys

**Review by xoxys — APPROVED** [review]
Maybe it makes sense to add those requirements to be plugin image.

**Comment by pat-s** [comment]
`helm` and the tools to install it are only used in cases where the plugin is used for helm releases, so bundling it by default doesn't make much sense.
Providing multiple images for different use cases is also cumbersome, so the usual conflict 🤷

**Comment by xoxys** [comment]
It was more about git and curl. However... Ill leave it to you.

**Pull request merged**
