### PR TITLE
Update READMEs

### PR DESCRIPTION
**Pull request by pat-s**
The step in the release workflow doesn't commit changes, only prints the result to stdout.

### CODE REVIEW

**Comment by pat-s** [comment]
ping @anbraten

**Comment by anbraten** [comment]
AFAIK it just did not, because the release pipeline always failed with the testing step. #67 hopefully fixed the first part. Now I have to fix this issue: https://ci.woodpecker-ci.org/repos/8958/pipeline/256/5

**Comment by pat-s** [comment]
Master/main mismatch

**Comment by anbraten** [comment]
The https://github.com/woodpecker-ci/woodpecker-ci.github.io still uses `master`. #68 should fix the issue from the last pipeline.

**Comment by pat-s** [comment]
Handled by CI after release.

**Pull request closed without merging**
