### PR TITLE
Don't commit submodule and `cr` assets

### LINKED ISSUE #34: Prevent commiting git submodule from release pipeline

### PR DESCRIPTION
**Pull request by pat-s**
- add `gitignore`
- remove unneeded assets

fix #34

### CODE REVIEW

**Comment by anbraten** [comment]
#39

**Comment by pat-s** [comment]
Oh no, again...

I'd argue that a `.gitignore` would still be good to have 😅

**Comment by pat-s** [comment]
@anbraten Which one do you prefer, this one or #39?

**Comment by pat-s** [comment]
This issue seems to let all CI runs in the other PRs fail - so should be merged to move on cleanly.

**Review by anbraten — APPROVED** [review]

**Comment by pat-s** [comment]
@anbraten The removed gitignore parts were there on purpose, following the templates of https://github.com/github/gitignore. Ofc up to you whether you want to have them but just that you are aware :)

**Pull request merged**
