### PR TITLE
add documentation for extra volume mounts in agent

### PR DESCRIPTION
**Pull request by CrimsonFez**
I noticed this documentation was either missing or had incorrect syntax.

### CODE REVIEW

**Comment by CrimsonFez** [comment]
My example for volumeMounts is bad. I will work on fixing this.

**Comment by pat-s** [comment]
@CrimsonFez Do you want to update your example still?

**Comment by CrimsonFez** [comment]
I did. It should be this commit https://github.com/woodpecker-ci/helm/pull/78/commits/b11c531850d88a9a4399881644a4fd83db99c8cd

**Comment by pat-s** [comment]
Ah sorry, totally overlooked this commit!

**Review by pat-s — APPROVED** [review]
LGTM. Thanks again for contributing!

**Pull request merged**
