### PR TITLE
feature: add custom command

### PR DESCRIPTION
**Pull request by eliasscosta**
This PR allows configuring a custom command for the containers.

### CODE REVIEW

**Comment by ymettier** [comment]
Hello,

I'm not a maintainer. I was just reading this with curiosity...

I'm wondering why there are so many changes like this, unrelated with the "command" feature :

```
- podSecurityContext: {}
+ podSecurityContext:
+   {}
```

Is this wanted or is this some magic from an IDE ?

Additional suggestion : think about also adding `args:`. Not only `command:`.

**Comment by anbraten** [comment]
Why would you like to change the command? Any specific options you want to pass?

**Comment by ymettier** [comment]
> I'm not a maintainer. I was just reading this with curiosity...

Let me explain why I was curious : I know a use-case for this. https://developer.hashicorp.com/vault/docs/platform/k8s/injector/examples#environment-variable-example

Sometimes you prefer to use an external solution to inject the secrets in the pods. In this case, an init container will be added automatically to the pod, thanks to annotations. It will put the secret in a file available from the other containers in the pod. The file can be formatted. The use-case is to format it in a way you can "source" it before running the command.
In the previous link, you can read this : 
```
          command:
            ['sh', '-c']
          args:
            ['source /vault/secrets/config && <entrypoint script>']
```

This is also why I suggested to add `args`.

@eliasscosta I'm also curious of your own use-case.

**Comment by anbraten** [comment]
@ymettier Thanks for the explanation.

**Comment by eliasscosta** [comment]
> > I'm not a maintainer. I was just reading this with curiosity...
> 
> Let me explain why I was curious : I know a use-case for this. https://developer.hashicorp.com/vault/docs/platform/k8s/injector/examples#environment-variable-example
> 
> Sometimes you prefer to use an external solution to inject the secrets in the pods. In this case, an init container will be added automatically to the pod, thanks to annotations. It will put the secret in a file available from the other containers in the pod. The file can be formatted. The use-case is to format it in a way you can "source" it before running the command. In the previous link, you can read this :
> 
> ```
>           command:
>             ['sh', '-c']
>           args:
>             ['source /vault/secrets/config && <entrypoint script>']
> ```
> 
> This is also why I suggested to add `args`.
> 
> @eliasscosta I'm also curious of your own use-case.

That is, exactly like that. I need to create a dynamic database string connection. My username and password are created by Vault and injected into an environment variable. And my injector needs to manipulate the field command, if the pod doesn't have they don't inject. 

I will update and args as well.

**Comment by eliasscosta** [comment]
> Hello,
> 
> I'm not a maintainer. I was just reading this with curiosity...
> 
> I'm wondering why there are so many changes like this, unrelated with the "command" feature :
> 
> ```
> - podSecurityContext: {}
> + podSecurityContext:
> +   {}
> ```
> 
> Is this wanted or is this some magic from an IDE ?
> 
> Additional suggestion : think about also adding `args:`. Not only `command:`.

Ah yes the vscode formmater made it.

**Comment by pat-s** [comment]
> Ah yes the vscode formatter made it.

We've had some discussions about this before 😅 I am usually the one causing it. It think we could solve it by some editorconfig rules. Let's see.

**Pull request merged**
