### PR TITLE
Replace secret check job with entry in notes template

### PR DESCRIPTION
**Pull request by meln5674**
Presently, there is a hook job to use openssl to print a random hex string, ideal for an agent secret. However, this has the following serious issues:

1. This is not necessary
2. This cannot be disabled
3. The generated value is not used
4. OpenSSL is not required here, as any valid string will be accepted as a secret
5. This job is not referenced anywhere in the notes or other documentation, and the user would need to know to go looking for it
6. The image is hard-coded, rendering the chart unusable in air-gapped or other restricted environments where this image is inaccessible

With these in mind, this patch removes this job and instead adds an equivalent printout to the NOTES.txt of the server chart. This can be viewed with the `--render-subchart-notes` flag when using the combined chart.

### CODE REVIEW

**Comment by pat-s** [comment]
Agreed. Combined with #228 the agent secret generation/handling will be improved by a lot.

**Comment by pat-s** [comment]
The agent secret is now created automatically and the secret check has been removed as well. Hence I am closing this as it is not needed anymore. 

Thanks for contributing and pointing this out!

**Comment by meln5674** [comment]
Unless I have overlooked something, the offending job is still there, so this remains an issue. The chart is unusable when that hard-coded image is not accessible, and there is now even less point in having that job at all.

**Comment by pat-s** [comment]
Yes, because there was no release yet.

**Comment by meln5674** [comment]
My apologies, I was still looking at 228. 247 addresses my concern, thank you.

**Pull request closed without merging**
